GLOBAL:
  loss: cross_entropy
  lrate: .1
  wreg: 0.
  wrt: L2

LAYERS: 
  input: 28
  hidden_layers:
    - size: 200
      act: leaky_relu
      wr: glorot
    - size: 70
      act: relu
      wr: glorot
    - size: 30
      act: tanh
      wr: glorot
    - size: 9
      act: relu
      wr: glorot
      br: (0 1)
  type: softmax

DATASET: 
  load: True
  name: 'doodle_data'