from pathlib import Path

YAML_CONFIG = Path('configs/basic_config.yaml')

DATA_FOLDER = Path('data/')
DATASET_SIZE = 10_000
BATCH_SIZE = DATASET_SIZE

DOODLE_ADDRESS = f"doodle_dataset_{DATASET_SIZE}"
DOODLE_IMAGE_SIZE = 28
DOODLE_NOISE = 0.
DOODLE_IS_CENTERED = True

VAL_SET_PROP = 20
TEST_SET_PROP = 10
TRAIN_SET_PROP = 100 - VAL_SET_PROP - TEST_SET_PROP

EPOCHS = 100